# Generated by Django 4.0.8 on 2022-12-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_comment_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
