# Generated by Django 4.0.8 on 2022-12-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_coverpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coverpage',
        ),
    ]
